/**
 * ==============================================================================
 *  OpenAPI · the browsable page
 *
 *  Swagger UI, served WITHOUT a single inline <script> or <style>.
 *
 *  That is not a style choice: the production Nginx sends
 *  `Content-Security-Policy: script-src 'self'`, so the page that the
 *  swagger-ui-dist package ships (which bootstraps itself from an inline
 *  script) would be blocked by the browser and the documentation would render
 *  blank. Here the HTML only references same-origin files - the bundle from
 *  the package and our own `init.js` - which the policy allows.
 *
 *  Both are produced as strings instead of being read from disk because `tsc`
 *  does not copy non-TypeScript files into `dist/`: this way the page works
 *  identically from `src` in development and from `dist` in the image, with no
 *  changes to the Dockerfile.
 * ==============================================================================
 */

/** Options handed to Swagger UI. Everything the tool offers that is useful here. */
export function initScript(specUrl: string): string {
  return `// Generated by apps/api/src/modules/openapi/ui.ts - do not edit in the browser.
window.addEventListener('load', function () {
  window.ui = SwaggerUIBundle({
    url: ${JSON.stringify(specUrl)},
    dom_id: '#swagger-ui',
    deepLinking: true,
    // Keeps the Authorize value across reloads: with a 15-minute token and an
    // API key that is shown once, re-typing it on every refresh is the fastest
    // way to make people stop using the docs.
    persistAuthorization: true,
    displayRequestDuration: true,
    tryItOutEnabled: true,
    filter: true,
    showExtensions: true,
    showCommonExtensions: true,
    // 'list' shows the operations of every tag straight away: with 104 of
    // them the page is long, but the filter box above makes it navigable and
    // an evaluator sees the whole surface without clicking eleven times.
    docExpansion: 'list',
    defaultModelsExpandDepth: 2,
    defaultModelRendering: 'example',
    tagsSorter: 'alpha',
    operationsSorter: 'alpha',
    syntaxHighlight: { activate: true, theme: 'tomorrow-night' },
    requestSnippetsEnabled: true,
    requestSnippets: {
      generators: {
        curl_bash: { title: 'cURL (bash)', syntax: 'bash' },
        curl_powershell: { title: 'cURL (PowerShell)', syntax: 'powershell' },
        curl_cmd: { title: 'cURL (CMD)', syntax: 'bash' },
      },
      defaultExpanded: false,
      languages: ['curl_bash'],
    },
    withCredentials: true,
    presets: [SwaggerUIBundle.presets.apis, SwaggerUIStandalonePreset],
    plugins: [SwaggerUIBundle.plugins.DownloadUrl],
    layout: 'StandaloneLayout',
    validatorUrl: null,
  });
});
`;
}

export function page(basePath: string, specUrl: string): string {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="robots" content="noindex" />
    <title>HelpDesk Lite API — reference</title>
    <link rel="stylesheet" href="${basePath}/assets/swagger-ui.css" />
    <link rel="icon" href="data:," />
  </head>
  <body>
    <div id="swagger-ui"></div>
    <script src="${basePath}/assets/swagger-ui-bundle.js"></script>
    <script src="${basePath}/assets/swagger-ui-standalone-preset.js"></script>
    <script src="${basePath}/init.js" data-spec="${specUrl}"></script>
  </body>
</html>
`;
}
